export const countries = [
  "Åland",
  "Afghanistan",
  "Africa",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Asia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Baker Island",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bonaire Saint Eustatius And Saba",
  "Bosnia And Herzegovina",
  "Botswana",
  "Brazil",
  "British Virgin Islands",
  "Bulgaria",
  "Burkina Faso",
  "Burma",
  "Burundi",
  "Côte D'Ivoire",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Colombia",
  "Comoros",
  "Congo (Democratic Republic Of The)",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czech Republic",
  "Denmark (Europe)",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Europe",
  "Falkland Islands (Islas Malvinas)",
  "Faroe Islands",
  "Federated States Of Micronesia",
  "Fiji",
  "Finland",
  "France (Europe)",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern And Antarctic Lands",
  "Gabon",
  "Gambia",
  "Gaza Strip",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea Bissau",
  "Guinea",
  "Guyana",
  "Haiti",
  "Heard Island And Mcdonald Islands",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle Of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kingman Reef",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Mali",
  "Malta",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Nepal",
  "Netherlands (Europe)",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "North America",
  "North Korea",
  "Northern Mariana Islands",
  "Norway",
  "Oceania",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestina",
  "Palmyra Atoll",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Barthélemy",
  "Saint Kitts And Nevis",
  "Saint Lucia",
  "Saint Martin",
  "Saint Pierre And Miquelon",
  "Saint Vincent And The Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome And Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South America",
  "South Georgia And The South Sandwich Isla",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard And Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor Leste",
  "Togo",
  "Tonga",
  "Trinidad And Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks And Caicas Islands",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom (Europe)",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Virgin Islands",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const defaultHistogramData = [
  {
    avg_real: 0.6279999999999999,
    avg_dp: 0.6756647977460891,
    avg_quantum_dp: -0.5781088117036048,
  },
  {
    avg_real: 0.7040000000000001,
    avg_dp: 0.7118242015834569,
    avg_quantum_dp: 0.7040010228736754,
  },
  {
    avg_real: 4.944,
    avg_dp: 5.032839783226529,
    avg_quantum_dp: 4.816677862688648,
  },
  {
    avg_real: 10.693,
    avg_dp: 10.712161876955937,
    avg_quantum_dp: 8.847857551080612,
  },
  {
    avg_real: 15.587,
    avg_dp: 15.685536890350459,
    avg_quantum_dp: 15.373818683034468,
  },
  {
    avg_real: 18.707,
    avg_dp: 18.720377348336147,
    avg_quantum_dp: 18.75551770366222,
  },
  {
    avg_real: 23.651,
    avg_dp: 23.475989514544587,
    avg_quantum_dp: 24.52162230560409,
  },
  {
    avg_real: 25.703000000000003,
    avg_dp: 25.976152798947723,
    avg_quantum_dp: 26.54948713593913,
  },
  {
    avg_real: 22.933000000000003,
    avg_dp: 22.869757166492512,
    avg_quantum_dp: 22.738900793582108,
  },
  {
    avg_real: 15.698,
    avg_dp: 15.464581450330765,
    avg_quantum_dp: 13.087954867448419,
  },
  {
    avg_real: 8.982999999999997,
    avg_dp: 9.116300797273512,
    avg_quantum_dp: 5.39796836288582,
  },
  {
    avg_real: 2.5569999999999995,
    avg_dp: 2.4929902221876983,
    avg_quantum_dp: 1.0418922814187335,
  },
];

export const months = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export const queryNames = [
  "Max Average Tempetures",
  "Median Average Tempetures",
  "Mean Average Tempetures",
  "Min Average Tempetures",
];

export const graphTitles = [
  "Max Average Tempetures Graph",
  "Median Average Tempetures Graph",
  "Mean Average Tempetures Graph",
  "Min Average Tempetures Graph",
];
